-- MySQL Script generated by MySQL Workbench
-- Tue 18 Jun 2019 16:09:04 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema small_business_db
-- -----------------------------------------------------
-- done by jmarkstar.
DROP SCHEMA IF EXISTS `small_business_db` ;

-- -----------------------------------------------------
-- Schema small_business_db
--
-- done by jmarkstar.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `small_business_db` ;
USE `small_business_db` ;

-- -----------------------------------------------------
-- Table `small_business_db`.`product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `small_business_db`.`product_category` ;

CREATE TABLE IF NOT EXISTS `small_business_db`.`product_category` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `small_business_db`.`product_brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `small_business_db`.`product_brand` ;

CREATE TABLE IF NOT EXISTS `small_business_db`.`product_brand` (
  `id_brand` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  PRIMARY KEY (`id_brand`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `small_business_db`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `small_business_db`.`product` ;

CREATE TABLE IF NOT EXISTS `small_business_db`.`product` (
  `id_prod` INT NOT NULL AUTO_INCREMENT,
  `id_brand` INT NOT NULL,
  `id_category` INT NOT NULL,
  `name` VARCHAR(85) NOT NULL,
  `image` VARCHAR(250) NULL,
  `thumb` VARCHAR(250) NULL,
  `description` VARCHAR(250) NULL,
  `weight` FLOAT NULL,
  `long_description` VARCHAR(50) NULL,
  PRIMARY KEY (`id_prod`),
  INDEX `fk_product_category_idx` (`id_category` ASC),
  INDEX `fk_product_brand_idx` (`id_brand` ASC),
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`id_category`)
    REFERENCES `small_business_db`.`product_category` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_brand`
    FOREIGN KEY (`id_brand`)
    REFERENCES `small_business_db`.`product_brand` (`id_brand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `small_business_db`.`provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `small_business_db`.`provider` ;

CREATE TABLE IF NOT EXISTS `small_business_db`.`provider` (
  `id_provider` INT NOT NULL,
  `company_name` VARCHAR(100) NULL,
  `contact_name` VARCHAR(100) NULL,
  `contact_phone` VARCHAR(15) NULL,
  PRIMARY KEY (`id_provider`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `small_business_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `small_business_db`.`user` ;

CREATE TABLE IF NOT EXISTS `small_business_db`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(150) NULL,
  `password` VARCHAR(100) NULL,
  `fullname` VARCHAR(150) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `small_business_db`.`product_input`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `small_business_db`.`product_input` ;

CREATE TABLE IF NOT EXISTS `small_business_db`.`product_input` (
  `id_input` INT NOT NULL AUTO_INCREMENT,
  `id_prod` INT NULL,
  `id_provider` INT NULL,
  `purchase_price` FLOAT NULL,
  `expiration_date` DATE NULL,
  `quantity` INT NULL DEFAULT 0,
  `creation_data` DATETIME NULL DEFAULT NOW(),
  `creation_user_id` INT NULL,
  PRIMARY KEY (`id_input`),
  INDEX `fk_input_product_idx` (`id_prod` ASC),
  INDEX `fk_input_provider_idx` (`id_provider` ASC),
  INDEX `fk_product_input_1_idx` (`creation_user_id` ASC),
  CONSTRAINT `fk_input_product`
    FOREIGN KEY (`id_prod`)
    REFERENCES `small_business_db`.`product` (`id_prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_input_provider`
    FOREIGN KEY (`id_provider`)
    REFERENCES `small_business_db`.`provider` (`id_provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_input_creator`
    FOREIGN KEY (`creation_user_id`)
    REFERENCES `small_business_db`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `small_business_db`.`product_output`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `small_business_db`.`product_output` ;

CREATE TABLE IF NOT EXISTS `small_business_db`.`product_output` (
  `id_output` INT NOT NULL AUTO_INCREMENT,
  `id_product_input` INT NULL,
  `quantity` INT NULL,
  `creation_data` DATETIME NULL,
  `creation_user_id` INT NULL,
  PRIMARY KEY (`id_output`),
  INDEX `fk_product_output_idx` (`id_product_input` ASC),
  INDEX `fk_product_output_creator_idx` (`creation_user_id` ASC),
  CONSTRAINT `fk_product_output_input`
    FOREIGN KEY (`id_product_input`)
    REFERENCES `small_business_db`.`product_input` (`id_input`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_output_creator`
    FOREIGN KEY (`creation_user_id`)
    REFERENCES `small_business_db`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `small_business_db`.`product_category`
-- -----------------------------------------------------
START TRANSACTION;
USE `small_business_db`;
INSERT INTO `small_business_db`.`product_category` (`id_category`, `name`) VALUES (1, 'Golosinas');
INSERT INTO `small_business_db`.`product_category` (`id_category`, `name`) VALUES (2, 'Gaseosas');
INSERT INTO `small_business_db`.`product_category` (`id_category`, `name`) VALUES (3, 'Licores');

COMMIT;


-- -----------------------------------------------------
-- Data for table `small_business_db`.`product_brand`
-- -----------------------------------------------------
START TRANSACTION;
USE `small_business_db`;
INSERT INTO `small_business_db`.`product_brand` (`id_brand`, `name`) VALUES (1, 'Alicorp');
INSERT INTO `small_business_db`.`product_brand` (`id_brand`, `name`) VALUES (2, 'Arcor');
INSERT INTO `small_business_db`.`product_brand` (`id_brand`, `name`) VALUES (3, 'Ambrosoli');

COMMIT;


-- -----------------------------------------------------
-- Data for table `small_business_db`.`product`
-- -----------------------------------------------------
START TRANSACTION;
USE `small_business_db`;
INSERT INTO `small_business_db`.`product` (`id_prod`, `id_brand`, `id_category`, `name`, `image`, `thumb`, `description`, `weight`, `long_description`) VALUES (1, 1, 1, 'Casino', 'https://img.gestion.pe/files/article_content_ge_fotos/files/crop/uploads/2019/03/24/5c97c54cee8b3.r_1553648458233.0-0-568-318.jpeg', 'https://www.alicorp.com.pe/alicorp/userfiles/cms/pagina/imagen/marca/item/galletas_casino_coco.jpg', 'Es una galleta muy rica xD', NULL, '1 PACK de 6 UNID');
INSERT INTO `small_business_db`.`product` (`id_prod`, `id_brand`, `id_category`, `name`, `image`, `thumb`, `description`, `weight`, `long_description`) VALUES (2, 3, 1, 'Mentitas', 'https://www.elparana.com/wp-content/uploads/2016/05/mentitas-de-ambrosoli.jpg', '', 'Son caramelos de menta', NULL, '1 CAJA de 24 UNID');

COMMIT;


-- -----------------------------------------------------
-- Data for table `small_business_db`.`provider`
-- -----------------------------------------------------
START TRANSACTION;
USE `small_business_db`;
INSERT INTO `small_business_db`.`provider` (`id_provider`, `company_name`, `contact_name`, `contact_phone`) VALUES (1, 'Ambrosoli', 'Jorge Perez', '999555333');
INSERT INTO `small_business_db`.`provider` (`id_provider`, `company_name`, `contact_name`, `contact_phone`) VALUES (2, 'Arcor', 'Maria Perea', '987412523');

COMMIT;


-- -----------------------------------------------------
-- Data for table `small_business_db`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `small_business_db`;
INSERT INTO `small_business_db`.`user` (`id_user`, `username`, `password`, `fullname`) VALUES (1, 'jmarkstar', 'abc123', 'Marco Estrella');

COMMIT;

